packages:
  platform: !include esp32.yaml

esphome:
  platformio_options:
    board_build.flash_mode: dio

psram:
  mode: quad
  speed: 80MHz

i2c:
  - id: cam_i2c
    sda: GPIO26
    scl: GPIO27

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_id: cam_i2c
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  name: cam
  resolution: 1080x1920

output:
  - platform: ledc
    channel: 2
    pin: GPIO4
    id: espCamLED
  - platform: gpio
    pin:
      number: GPIO33
      inverted: True
    id: gpio_33

light:
  - platform: monochromatic
    output: espCamLED
    id: esp_cam_light
    name: esp-cam light
  - platform: binary
    output: gpio_33
    name: esp-cam led  